# Generated by Django 3.2.6 on 2023-12-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('hotel_id', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_id', models.CharField(default=True, max_length=50)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
