# Generated by Django 3.2.6 on 2023-12-31 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_dish_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish_category',
            name='employee_id',
        ),
    ]
