# Generated by Django 3.2.6 on 2023-12-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_dish_category_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(default=0)),
                ('hotel_id', models.CharField(blank=True, max_length=100, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
