# Generated by Django 3.2.6 on 2023-12-31 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_dish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='category_name',
            new_name='dish_category_id',
        ),
    ]
