# Generated by Django 3.2.6 on 2023-12-31 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20231231_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_category',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.dish_category'),
        ),
    ]
