# Generated by Django 5.0 on 2023-12-31 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_dish_dish_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.dish_category'),
        ),
    ]
