# Generated by Django 3.2.6 on 2023-12-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_dish_dish_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
