# Generated by Django 3.2.6 on 2023-12-31 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_dish_dish_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='order.dish_category'),
        ),
    ]
