# Generated by Django 3.2.6 on 2023-12-31 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='hotel_id',
            new_name='hotel',
        ),
    ]
