# Generated by Django 3.2.6 on 2024-01-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_rename_hotel_id_table_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_mobile',
            field=models.IntegerField(default=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='mobile',
            field=models.IntegerField(unique=True),
        ),
    ]
