# Generated by Django 3.2.6 on 2024-01-03 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20240103_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('dish', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='order.dish')),
                ('employee', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='order.employee')),
                ('hotel', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='order.hotel')),
                ('table', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='order.table')),
            ],
        ),
    ]
