# Generated by Django 3.2.6 on 2024-01-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
