# Generated by Django 3.2.6 on 2024-01-03 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_cart_added_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='total_price',
        ),
    ]
