# Generated by Django 5.0 on 2024-01-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_rename_price_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
