# Generated by Django 5.0 on 2024-01-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_cart_cook_status_alter_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='chef_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
