# Generated by Django 3.2.6 on 2024-01-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_cart_chef_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='note',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
