# Generated by Django 3.2.6 on 2024-01-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20240105_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
