# Generated by Django 3.2.6 on 2024-01-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='table_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
