# Generated by Django 3.2.6 on 2024-01-06 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_cart_table_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='order.employee')),
                ('hotel', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='order.hotel')),
                ('table', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='order.table')),
            ],
        ),
    ]
