# Generated by Django 3.2.6 on 2024-01-07 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_ordermaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaster',
            name='employee',
        ),
    ]
