# Generated by Django 3.2.6 on 2024-01-07 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_remove_ordermaster_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaster',
            name='total_price',
        ),
    ]
