# Generated by Django 3.2.6 on 2024-01-07 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_remove_ordermaster_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='order_filter',
            field=models.IntegerField(default=True),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(default=True)),
                ('dish_name', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0, null=True)),
                ('total_price', models.FloatField(default=0, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_filter', models.IntegerField(default=True)),
                ('table', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='order.table')),
            ],
        ),
    ]
