# Generated by Django 3.2.6 on 2024-01-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_auto_20240107_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='total_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
