# Generated by Django 3.2.6 on 2024-01-07 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_ordermaster_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='table',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='hotel',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='order.hotel'),
        ),
    ]
