# Generated by Django 3.2.6 on 2024-01-08 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_marketing_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='marketing_admin_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hotel',
            name='marketing_employee',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='order.marketing_employee'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
