# Generated by Django 3.2.6 on 2024-01-12 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_alter_cart_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.employee'),
        ),
    ]
