# Generated by Django 3.2.6 on 2024-01-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_auto_20240113_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='dish_marathi_name',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
