# Generated by Django 3.2.6 on 2024-01-13 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_cart_dish_marathi_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_marathi_name', models.CharField(default=True, max_length=100)),
                ('table_number', models.CharField(blank=True, max_length=100, null=True)),
                ('chef_id', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0, null=True)),
                ('total_price', models.FloatField(default=0, null=True)),
                ('note', models.CharField(max_length=100, null=True)),
                ('cook_status', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Packed'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='pending', max_length=50)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('dish', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='order.dish')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.employee')),
                ('hotel', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='order.hotel')),
                ('table', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='order.table')),
            ],
        ),
    ]
